In [ ]:
import tensorflow as tf

In [3]:
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
vector= tf.constant([7,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7])>

In [5]:
matrix= tf.constant([[1,2],
                    [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [6]:
tensor= tf.constant([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])>

In [7]:
print("scalar",scalar.ndim)
print("vector",vector.ndim)
print("matrix",matrix.ndim)
print("tensor",tensor.ndim)

scalar 0
vector 1
matrix 2
tensor 3


In [8]:
# variable
v_vector= tf.Variable([7])
v_vector

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([7])>

In [9]:
v_vector[0].assign(1)

<tf.Variable 'UnreadVariable' shape=(1,) dtype=int32, numpy=array([1])>

In [10]:
# random tensor
random1= tf.random.Generator.from_seed(42)
random1= random1.normal((3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [11]:
# random tensor
random2= tf.random.Generator.from_seed(42)
random2= random2.normal((3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [12]:
random2==random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [13]:
tf.random.shuffle(random2)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702]], dtype=float32)>

In [14]:
ones_t= tf.ones([3,3])
ones_t

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [15]:
zeros_t= tf.zeros([3,3])
zeros_t

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [16]:
import numpy as np

In [17]:
arr= np.arange(1,25,dtype=np.int32)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [18]:
tensor_c= tf.constant(arr)
tensor_c

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [19]:
tensor_v= tf.Variable(arr)
tensor_v

<tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [20]:
2*3*4

24

In [21]:
tensor_c1= tf.constant(arr,shape=(2,3,4))
tensor_c1

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [22]:
tensor_c2= tf.constant(arr,shape=(2,2,6))
tensor_c2

<tf.Tensor: shape=(2, 2, 6), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]])>

In [23]:
# indexing
tensor_c1[0]

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])>

In [24]:
tensor_c1[1]

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

In [25]:
tensor_c1[:1,:1,:]

<tf.Tensor: shape=(1, 1, 4), dtype=int32, numpy=array([[[1, 2, 3, 4]]])>

In [26]:
tensor_c1[:,:1,:1]

<tf.Tensor: shape=(2, 1, 1), dtype=int32, numpy=
array([[[ 1]],

       [[13]]])>

In [27]:
tensor_c3= tf.expand_dims(tensor_c1,-1)
tensor_c3

<tf.Tensor: shape=(2, 3, 4, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 2],
         [ 3],
         [ 4]],

        [[ 5],
         [ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11],
         [12]]],


       [[[13],
         [14],
         [15],
         [16]],

        [[17],
         [18],
         [19],
         [20]],

        [[21],
         [22],
         [23],
         [24]]]])>

In [28]:
# oprators(+,-,*,/)
t= tf.constant([[2,3],
             [5,6]])
t

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]])>

In [29]:
t+1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [6, 7]])>

In [30]:
t-1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]])>

In [31]:
t*2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  6],
       [10, 12]])>

In [32]:
t/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 1.5],
       [2.5, 3. ]])>

In [33]:
# element to element multiplication
x= tf.constant([[1,2,3],
                [4,5,6],
                [7,8,9]])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [34]:
y= tf.constant([[1,2,3],
                [2,2,2],
                [7,8,9]])
y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 2, 2],
       [7, 8, 9]])>

In [35]:
x*y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [ 8, 10, 12],
       [49, 64, 81]])>

In [36]:
z= tf.constant([[3,2],
               [8,9]])
z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 2],
       [8, 9]])>

In [37]:
z*z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9,  4],
       [64, 81]])>

In [38]:
x1= tf.constant([[3,2],
                 [6,5],
                 [8,9]])
y1= tf.constant([[3,2],
                 [4,2],
                 [8,9]])

In [39]:
x1*y1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9,  4],
       [24, 10],
       [64, 81]])>

In [40]:
# type casting
tf.cast(x1,dtype=tf.int64)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[3, 2],
       [6, 5],
       [8, 9]], dtype=int64)>

In [41]:
tf.cast(x1,dtype=tf.float32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 2.],
       [6., 5.],
       [8., 9.]], dtype=float32)>

In [42]:
# aggregation function(sum,max,min,etc)
tf.reduce_sum(x1)

<tf.Tensor: shape=(), dtype=int32, numpy=33>

In [43]:
tf.math.reduce_std(tf.cast(x1,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [44]:
tf.math.reduce_variance(tf.cast(x1,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=6.25>

In [49]:
# to find the index of highest number
tf.argmax(x1)


<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2], dtype=int64)>

In [50]:
tf.argmin(x1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0], dtype=int64)>

In [51]:
u= tf.constant(np.arange(1,25))
u

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [54]:
tf.argmax(u)

<tf.Tensor: shape=(), dtype=int64, numpy=23>

In [57]:
tf.argmin(u)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [55]:
u[tf.argmax(u)]

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [56]:
u[tf.argmin(u)]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [58]:
# GPU
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [60]:
list= [0,1,2,3]
tf.one_hot(list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [61]:
tf.one_hot(list,depth=4,on_value="Yes",off_value="No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>